name: Run Automated UI Tests

on:
  workflow_dispatch:  # Manual trigger ("Run workflow" button)
  push:
    branches:
      - main  # Or whichever branch you want
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission to Gradle
      run: chmod +x ./gradlew

    - name: Run Tests
      run: ./gradlew test --stacktrace

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: build/reports/tests/test
